#!/bin/sh

CONTAINER_PG="pgdemo"

MYUID=$(id -u "$USER")
MYGID=$(id -g "$USER")

CMD="livecompare my_project.ini"
docker exec -it -u "${MYUID}:${MYGID}" -w /mnt $CONTAINER_PG $CMD
#docker exec -it -u root -w /mnt $CONTAINER_PG $CMD

echo
echo "This was the command executed by this script: $CMD"
