#!/bin/sh

CONTAINER_PG="pgdemo"
IMAGE_PG="pgdemo"
CONTAINER_ORA="orademo"
IMAGE_ORA="orademo"

CWD=$(pwd)
DIR=$(dirname "$0")

docker run -d --name $CONTAINER_ORA --shm-size=1g -p 1521:1521 $IMAGE_ORA
docker run -d -p 8443:8443 --name $CONTAINER_PG -v "${CWD}/${DIR}:/mnt" $IMAGE_PG

echo "You may monitor Oracle's container creation with: docker logs -f $CONTAINER_ORA"
