#!/bin/sh

CONTAINER_PG="pgdemo"
CMD="/usr/edb/migrationtoolkit/bin/runMTK.sh -dataOnly -truncLoad HRPLUS"
docker exec -it -u root $CONTAINER_PG sh -c "$CMD"
echo "This was the command executed by this script: $CMD"
